#!/usr/bin/env python3
import logging
import os
import traceback
from datetime import datetime
from email import message_from_string
from email.mime.text import MIMEText
from email.utils import format_datetime, mktime_tz, parsedate_tz
from imaplib import IMAP4_SSL
from random import SystemRandom
from smtplib import SMTP
from string import ascii_letters, digits
from tempfile import NamedTemporaryFile
from time import sleep
from typing import Optional

import config

random = SystemRandom()


def check_mail(destination):
    subject_identifier = ''.join(random.choice(ascii_letters + digits) for i in range(30))
    subject = f"testmail {subject_identifier}"

    send_test_message(subject, destination)

    retry = 0
    while True:
        sleep(2)

        logging.info('trying to fetch test mail, retry %s', retry)
        date = get_email_date(subject, destination)
        if date:
            break
        retry += 1
        if retry > config.MAX_RETRIES:
            logging.error('failed to fetch test mail')
            return False

    if not date:
        logging.error('failed to get the date of the last email')
        return False

    return True


def get_email_date(subject, destination):
    """
    Get the date of the email with specified subject and delete it.

    Warning: no escaping of subject is performed.
    """
    most_recent_date = None

    with IMAP4_SSL(destination['host']) as conn:
        conn.login(destination['user'], destination['password'])
        conn.select(destination['mailbox'])

        logging.info('connected to mailbox %s', destination['mailbox'])

        state, matches = conn.search(None, '(SUBJECT "{}")'.format(subject))
        if state != 'OK':
            logging.error('failure listing messages')
            return
        matches = [match for match in matches[0].split(b' ') if match]
        logging.info('found %s matching message(s)', len(matches))
        for match in matches:
            state, msg = conn.fetch(match, '(RFC822)')
            if state != 'OK':
                logging.error('failure fetching message')
                return
            msg = message_from_string(msg[0][1].decode())
            msg_date = datetime.fromtimestamp(
                mktime_tz(parsedate_tz(msg['Date'])))
            logging.info('fetched message %s, date %s', int(match), msg_date)

            if most_recent_date is None or msg_date > most_recent_date:
                most_recent_date = msg_date

            conn.store(match, '+FLAGS', '\\Deleted')

        logging.info('expunging mailbox')
        conn.expunge()

    return most_recent_date


def send_test_message(subject, destination):
    mail = MIMEText(
        'This is a test email. Its sole purpose is to act as a test email\n'
        'whose existence will confirm that email delivery is working\n'
        'as it should.')
    mail['Subject'] = subject
    mail['From'] = config.source['sender']
    mail['To'] = destination['recipient']
    mail['Date'] = format_datetime(datetime.utcnow())
    with SMTP(config.source['host'], config.source['port']) as smtp:
        smtp_user = config.source.get('user')
        smtp_password = config.source.get('password')
        smtp_tls = config.source.get('tls')
        if smtp_tls:
            smtp.starttls()
        if smtp_user and smtp_password:
            smtp.login(smtp_user, smtp_password)

        smtp.sendmail(
            config.source['sender'],
            destination['recipient'],
            mail.as_string())
    logging.info('sent test email with subject "%s"', subject)


def write_textfile(results):
    with NamedTemporaryFile(mode='w', delete=False) as textfile:
        for result in results:
            textfile.write(
                '# HELP probe_success Whether the mail delivery was successful\n')
            textfile.write('# TYPE probe_success gauge\n')
            textfile.write('probe_success_{} {}\n'.format(result, int(results[result])))

        textfile.flush()
        os.fsync(textfile.fileno())
        file_name = textfile.name
    os.rename(file_name, config.TEXTFILE_PATH)


if __name__ == '__main__':
    logging.basicConfig(
        format='%(asctime)-15s: %(message)s', level=config.LOG_LEVEL)

    result = False
    results = {}
    for destination in config.destinations:
        try:
            if config.destinations[destination]['enabled']:
                results[destination] = check_mail(config.destinations[destination])
        except Exception:
            logging.error('a failure occured: %s', traceback.format_exc())
            results[destination] = False

    write_textfile(results)
